version: "3.8"

networks:
  elastic:
    external: true


services:
  proxy:
    image: nginx
    volumes:
      - ./docker/proxy/proxy.conf:/tmp/nginx.conf
    env_file:
      - ./app.env
    environment:
      ES_ADDR: "es:9200"
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - es
    networks:
      - elastic

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: es
    env_file:
      - ./app.env
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
